# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
envlist = lint, static, unit
isolated_build=true

[vars]
src_path = {toxinidir}/src
tst_path = {toxinidir}/tests
all_path = {[vars]src_path} {[vars]tst_path}
uv_flags = --frozen --isolated --extra=dev

[testenv]
allowlist_externals = uv
basepython = python3
setenv =
  PYTHONPATH = {[vars]src_path}
  PY_COLORS=1
passenv =
  PYTHONPATH
  HOME
  PATH

[testenv:lock]
description = Update uv.lock with the latest deps
commands =
  uv lock --upgrade --no-cache

[testenv:fmt]
description = Apply coding style standards to code
commands =
    uv run {[vars]uv_flags} black {[vars]all_path}
    uv run {[vars]uv_flags} ruff check --fix {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
commands =
    uv run {[vars]uv_flags} codespell {[vars]all_path} --ignore-words-list=aNULL
    uv run {[vars]uv_flags} ruff check {[vars]all_path}
    uv run {[vars]uv_flags} black --check --diff {[vars]all_path}

[testenv:static]
description = Run static analysis checks
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/lib
commands =
    uv run {[vars]uv_flags} pyright {[vars]src_path}

[testenv:unit]
description = Run unit tests
setenv =
    PYTHONPATH = {[vars]src_path}
commands =
    uv run {[vars]uv_flags} python -m doctest {[vars]src_path}/cosl/mandatory_relation_pairs.py
    uv run {[vars]uv_flags} sh -c 'stat cos-tool-amd64 > /dev/null 2>&1 || \
        curl -L -O https://github.com/canonical/cos-tool/releases/latest/download/cos-tool-amd64'
    uv run {[vars]uv_flags} sh -c 'chmod 755 cos-tool-amd64'
    uv run {[vars]uv_flags} pytest {tty:--color=yes} --cov={[vars]src_path} --cov-config={tox_root}/pyproject.toml \
        --cov-report=term-missing \
        ;    for us
        --cov-report=html:{tox_root}/results/html-cov/ \
        ;    for tiobe
        --cov-report=xml:{tox_root}/results/coverage-{env_name}.xml \
        ;    for sparta
        --cov-report=json:{tox_root}/results/tox-{env_name}.json \
        --junit-xml={tox_root}/results/test-results-{env_name}.xml {posargs}
