name: Distributed Solutions Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test-distributed-charms:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: canonical/tempo-coordinator-k8s-operator
            commit: 82f832cdf4d40300366a86f752c8bbfbdde41382  # unreleased rev, 5 sept 2024
          - repo: canonical/tempo-worker-k8s-operator
            commit: 74c3f8057d81a9e91088b54752b7b26daf43501e  # rev11, 5 sept 2024

    steps:
      - name: Checkout the ${{ matrix.repo }} repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          ref: ${{ matrix.commit }}

      - name: Update 'cosl' dependency in test charm to this branch
        run: |
          sed -i -e "/^cosl[ ><=]/d" -e "/canonical\/cos-lib/d" -e "/#egg=cosl/d" requirements.txt
          echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=cosl" >> requirements.txt

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Run the charm's unit & scenario tests
        run: tox -vve unit,scenario

      - name: Run the charm's static analysis checks
        run: tox -vve static-charm,static-lib

      - name: Run the charm's integration tests
        run: tox -vve integration