name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  quality:
    uses: ./.github/workflows/pull-request.yaml
  release:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    needs: [ quality ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install wheel
        run: python3 -m pip install --upgrade build
      - name: Build
        run: python3 -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
